# Generated by Django 4.0.6 on 2022-08-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='display',
        ),
        migrations.RemoveField(
            model_name='post',
            name='suggestedTimes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uploaded_from',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usersIn',
        ),
    ]
