# Generated by Django 4.0.6 on 2022-08-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_content_type_remove_post_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageUrl',
        ),
    ]
