# Generated by Django 4.0.6 on 2022-08-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_like_create_at_remove_like_like_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='create_at',
        ),
    ]
