# Generated by Django 4.0.6 on 2022-08-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_collection_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
