# Generated by Django 4.0.6 on 2022-08-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_like_user_remove_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
