# Generated by Django 4.0.6 on 2022-08-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
